version: '3.9'

services:
  employee-manager-poc-api:
    container_name: employee-manager-poc-api
    hostname: employee-manager-poc-api
    image: employee-manager-poc-api:latest
    build:
      context: ./
      target: development
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    command: ['npm', 'start']
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      MONGO_URL: mongodb://root:123456@mongo:27017/employee-manager-poc?authSource=admin
    networks:
      - employee-manager-poc-network

  employee-manager-poc-mongodb:
    container_name: employee-manager-poc-mongodb
    hostname: mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: employee-manager-poc
    ports:
      - '27017:27017'
    volumes:
      - database:/data/db
    networks:
      - employee-manager-poc-network

volumes:
  node_modules:
  database:

networks:
  employee-manager-poc-network:
    driver: bridge
